CREATE TABLE `authors` (
  `ID` char(32) NOT NULL,
  `CHANGED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FIRST_NAME` varchar(20) NOT NULL,
  `LAST_NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_AUTHORS` (`FIRST_NAME`,`LAST_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
