CREATE TABLE `books_to_authors` (
  `BOOK_ID` char(32) NOT NULL,
  `AUTHOR_ID` char(32) NOT NULL,
  KEY `FK_AUTHORS` (`AUTHOR_ID`),
  KEY `FK_BOOKS` (`BOOK_ID`),
  CONSTRAINT `FK_AUTHORS` FOREIGN KEY (`BOOK_ID`) REFERENCES `books` (`ID`),
  CONSTRAINT `FK_BOOKS` FOREIGN KEY (`AUTHOR_ID`) REFERENCES `authors` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
