CREATE TABLE `reviews` (
  `ID` char(32) NOT NULL,
  `CHANGED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENT` longtext NOT NULL,
  `COMMENTER_NAME` varchar(20) NOT NULL,
  `RATING` int(11) DEFAULT NULL,
  `BOOK_ID` char(32) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_BOOK` (`BOOK_ID`),
  CONSTRAINT `FK_BOOK` FOREIGN KEY (`BOOK_ID`) REFERENCES `books` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
