CREATE TABLE `books` (
  `ID` char(32) NOT NULL,
  `CHANGED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `AVG_RATING` double DEFAULT NULL,
  `ISBN` bigint(20) NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `PUBLISH_YEAR` int(11) NOT NULL,
  `PUBLISHER` varchar(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_BOOKS` (`ISBN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
