CREATE TABLE `reviews` (
  `ID` BINARY(16) NOT NULL ,
  `CHANGED` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMMENT` longtext NOT NULL,
  `COMMENTER_NAME` varchar(255) NOT NULL,
  `RATING` int(11) DEFAULT NULL,
  `BOOK_ID` BINARY(16) NOT NULL ,
  PRIMARY KEY (`ID`),
  KEY `FK_d1dn979slijcn116escftr7tg` (`BOOK_ID`),
  CONSTRAINT `FK_d1dn979slijcn116escftr7tg` FOREIGN KEY (`BOOK_ID`) REFERENCES `books` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;